# Generated by Django 5.0.6 on 2024-06-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
